// // ignore
// // Code generated by lens-vm-go-sdk. DO NOT EDIT.
package rename

// import (
// 	sdk "github.com/lens-vm/lens-vm-go-sdk"
// 	"github.com/lens-vm/lens-vm-go-sdk/types"
// )

// /******* LensVM module import functions *******/

// //export lensvm_exec_hoist
// func _lensvm_exec_hoist(forward bool, argBuffer *byte, argSize int32, dataBuffer *byte, dataSize int32) types.Status

// func wrapped_lensvm_exec_hoist(forward bool, argBuffer *byte, argSize int32, dataBuffer *byte, dataSize int32) types.Status {
// 	return _lensvm_exec_hoist(forward, argBuffer, argSize, dataBuffer, dataSize)
// }

// func (ctx *RenameContext) ResolveImports() []sdk.Import {
// 	return []sdk.Import{
// 		sdk.NewImport("hoist", wrapped_lensvm_exec_hoist),
// 	}
// }

// /******* LensVM module export functions *******/

// // //export lensvm_exec_rename
// // func _lensvm_exec_rename(forward bool, argBufferStart int32, argSize int32, dataBufferStart int32, dataSize int32) types.Status {
// // 	return sdk.Exec("rename", forward, argBufferStart, argSize, dataBufferStart, dataSize)
// // }
